name:                effect
version:             0.1.0.0
github:              "re-xyr/effect"
license:             BSD3
author:              "daylily"
maintainer:          "xy.r@outlook.com"
copyright:           "2021 daylily"

extra-source-files: []

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/daylily/effect#readme>

dependencies:
- async
- base
- containers
- exceptions
- monad-control
- primitive
- process
- resourcet
- stm
- template-haskell
- th-abstraction
- transformers-base
- typerep-map
- unliftio

flags:
  dynamic-ioe:
    description: |
      Make @IOE@ a real effect. This is only for reference purposes and should not be enabled in production code.
    manual: true
    default: false

ghc-options:
# - -O2
- -Wall
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wincomplete-record-updates
- -Widentities

when:
- condition: flag(dynamic-ioe)
  cpp-options:
  - -DDYNAMIC_IOE

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- ConstraintKinds
- DataKinds
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- MagicHash
- MultiParamTypeClasses
- PolyKinds
- RankNTypes
- RoleAnnotations
- ScopedTypeVariables
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances

library:
  source-dirs: src

tests:
  effect-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - effect
    - hspec
    - lifted-base
    - QuickCheck
    default-extensions:
    - DeriveAnyClass
    - DeriveGeneric
    - DerivingVia
