name:                cleff
version:             0.1.0.0
github:              "re-xyr/cleff"
license:             BSD3
author:              "Xy Ren"
maintainer:          "xy.r@outlook.com"
copyright:           "2021 Xy Ren"

tested-with:
- GHC == 8.6.5
- GHC == 8.8.4
- GHC == 8.10.7
- GHC == 9.0.2

extra-source-files:
- CHANGELOG.md
- README.md

synopsis:            Fast and concise extensible effects
category:            Control, Effect, Language

description:         Please see the README on GitHub at <https://github.com/re-xyr/cleff#readme>

dependencies:
- atomic-primops >= 0.8 && < 0.9
- base >= 4.12 && < 5
- containers >= 0.6 && < 0.7
- exceptions >= 0.10 && < 0.11
- microlens >= 0.4.9 && < 0.5
- monad-control >= 1 && < 1.1
- primitive >= 0.6 && < 0.8
- template-haskell >= 2.14 && < 3
- th-abstraction >= 0.2.11 && < 0.5
- transformers >= 0.5 && < 0.7
- transformers-base >= 0.4.5 && < 0.5
- unliftio >= 0.2.8 && < 0.3

flags:
  dynamic-ioe:
    description: |
      Make @IOE@ a real effect. This is only for reference purposes and should not be enabled in production code.
    manual: true
    default: false

ghc-options:
- -Wall
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-deriving-strategies
- -Wpartial-fields
- -Wunused-type-patterns
# - -ddump-simpl
# - -ddump-to-file
# - -dsuppress-all
# - -dsuppress-uniques

when:
- condition: flag(dynamic-ioe)
  cpp-options:
  - -DDYNAMIC_IOE

default-extensions:
- BangPatterns
- BlockArguments
- ConstraintKinds
- DataKinds
- DerivingVia
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- NoStarIsType
- PatternSynonyms
- PolyKinds
- QuantifiedConstraints
- RankNTypes
- RoleAnnotations
- ScopedTypeVariables
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances
- UnicodeSyntax
- ViewPatterns

library:
  source-dirs: src
  ghc-options:
  - -Wmissing-export-lists

tests:
  cleff-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cleff
    - extra
    - hspec
    - lifted-base
    - QuickCheck
    default-extensions:
    - DeriveAnyClass
    - DeriveGeneric

  cleff-example:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cleff
    - extra
    default-extensions:
    - DeriveAnyClass
