resolver: lts-18.26

packages:
- .
- ./cleff-plugin

ghc-options:
  "$everything": -haddock

extra-deps:
- polysemy-1.7.1.0
- github: arybczak/effectful
  commit: a757b8ffd0d01d3b38f34371d53b84565dc2dfff
  subdirs:
  - effectful
  - effectful-core
  - effectful-th
