name:                cleff-kvstore
version:             0.1.0.0
github:              "re-xyr/cleff"
license:             BSD3
author:              "daylily"
maintainer:          "xy.r@outlook.com"
copyright:           "2021 daylily"

extra-source-files:
- CHANGELOG.md

synopsis:            Key-value store effect for the cleff library
category:            Control

description:         Please see the README on GitHub at <https://github.com/re-xyr/cleff#readme>

dependencies:
- base >= 4.12 && < 5
- cleff >= 0.1 && < 0.2
- containers >= 0.6 && < 0.7
- extra >= 1.6 && < 1.8
- hashable >= 1.2 && < 1.4
- unordered-containers >= 0.2.9 && < 0.3

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wincomplete-record-updates
- -Widentities

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GADTs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- ScopedTypeVariables
- TemplateHaskell
- TypeApplications
- TypeOperators

library:
  source-dirs: src
